encryptPassword=false
storePasswordAsHex=false
initialPasswordForAdmin=admin
startInLastVisitedModule=true
showModulesMenuWhenNotLogged=false
showApplicationName=true
showOrganizationOnSignIn=false
showListOfOrganizationsOnSignIn=false
updateNaviOXTablesInOrganizationsOnStartup=true


