encryptPassword=false
storePasswordAsHex=false
initialPasswordForAdmin=admin
startInLastVisitedModule=false
rememberVisitedModules=false
allModulesNamesProviderClass=com.aptispace.web.AptiSpaceModulesNamesProvider
showModulesMenuWhenNotLogged=false
showApplicationName=true
showOrganizationOnSignIn=false
showListOfOrganizationsOnSignIn=false
updateNaviOXTablesInOrganizationsOnStartup=true


